using System.IO.Compression;
using System.Text;
using VisualNovelResourceTool.Core;

if (args.Length > 0)
{
    if(args[0]=="--scan"&&args.Length==2){foreach(var result in new GameScanner().Scan(args[1]))Console.WriteLine($"{result.Kind} | {result.Support} | {result.Format} | {result.Path}");return 0;}
    if(args[0]=="--classify"&&args.Length>=2){foreach(var source in args.Skip(1)){IEnumerable<string> names=Path.GetExtension(source).Equals(".xp3",StringComparison.OrdinalIgnoreCase)?Xp3Archive.Open(source).Entries.Select(e=>e.Name):RpaArchive.Open(source).Entries.Select(e=>e.Name);var list=names.ToArray();Console.WriteLine(source);foreach(var group in list.GroupBy(AssetClassifier.Classify).OrderBy(g=>g.Key))Console.WriteLine($"  {group.Key}: {group.Count():N0}");Console.WriteLine("  TOP: "+string.Join(", ",list.Select(n=>n.Replace('\\','/').Split('/')[0]).GroupBy(x=>x).OrderByDescending(g=>g.Count()).Take(12).Select(g=>$"{g.Key}={g.Count()}")));}return 0;}
    if(args[0]=="--xp3-check"&&args.Length==2){var a=Xp3Archive.Open(args[1]);var image=a.Entries.First(e=>AssetClassifier.IsImage(e.Name));var bytes=await a.ReadEntryAsync(image);Console.WriteLine($"PREVIEW {image.Name} {bytes.Length:N0} bytes {Convert.ToHexString(bytes.AsSpan(0,Math.Min(12,bytes.Length)))}");var problematic=a.Entries.Where(e=>e.Name.IndexOfAny(Path.GetInvalidFileNameChars())>=0).ToArray();var root=Path.Combine(Path.GetTempPath(),"vnrt-xp3-check-"+Guid.NewGuid().ToString("N"));var result=await a.ExtractAsync(problematic,root,true);Console.WriteLine($"INVALID {problematic.Length}, EXTRACTED {result.Extracted}, FAILED {result.Failed}, RENAMED {result.Renamed}, REPORT {File.Exists(Path.Combine(root,"_提取记录.txt"))}");Directory.Delete(root,true);return 0;}
    if(args[0]=="--extract"&&args.Length==3){var source=args[1];var output=args[2];ExtractionSummary result;if(Path.GetExtension(source).Equals(".xp3",StringComparison.OrdinalIgnoreCase)){var a=Xp3Archive.Open(source);result=await a.ExtractAsync(a.Entries,output,true);}else{var a=DpmxArchive.Open(source);result=await a.ExtractAsync(a.Entries,output,true);}Console.WriteLine($"EXTRACTED {result.Extracted} {result.BytesWritten}");return 0;}
    if(args[0]=="--extract-first-video"&&args.Length==3){var a=RpaArchive.Open(args[1]);var entry=a.Entries.First(e=>Path.GetExtension(e.Name).Equals(".webm",StringComparison.OrdinalIgnoreCase));var result=await a.ExtractAsync([entry],args[2],true);Console.WriteLine(Path.Combine(args[2],entry.Name.Replace('/',Path.DirectorySeparatorChar)));Console.WriteLine($"EXTRACTED {result.Extracted} {result.BytesWritten}");return 0;}
    if(args[0]=="--pak-check"&&args.Length==2){var a=RpgMakerPakArchive.Open(args[1]);var entry=a.Entries.First(e=>AssetClassifier.IsImage(e.Name));var bytes=await a.ReadEntryAsync(entry);var output=Path.Combine(Path.GetTempPath(),"vnrt-pak-check-"+Guid.NewGuid().ToString("N"));var result=await a.ExtractAsync([entry],output,true);Console.WriteLine($"PAK {a.Entries.Count} PREVIEW {entry.Name} {bytes.Length} {Convert.ToHexString(bytes.AsSpan(0,Math.Min(8,bytes.Length)))} EXTRACTED {result.Extracted}");Directory.Delete(output,true);return 0;}
    if(args[0]=="--rpg-check"&&args.Length==2){var a=RpgMakerProject.Open(args[1]);var entry=a.Entries.First(e=>AssetClassifier.IsImage(e.RelativeOutputPath));var output=Path.Combine(Path.GetTempPath(),"vnrt-rpg-check-"+Guid.NewGuid().ToString("N"));var result=await a.ExtractAsync([entry],output,true);Console.WriteLine($"RPG {a.Entries.Count} VISUAL {a.Entries.Count(e=>AssetClassifier.Matches(e.RelativeOutputPath,AssetCategory.Images))} SAMPLE {entry.RelativeOutputPath} ENCRYPTED {entry.Encrypted} EXTRACTED {result.Extracted}");Directory.Delete(output,true);return 0;}
    if(args[0]=="--loose-check"&&args.Length==2){var a=LooseResourceProject.Open(args[1]);var entry=a.Entries.First(e=>AssetClassifier.IsImage(e.Name));var bytes=await a.ReadEntryAsync(entry);var output=Path.Combine(Path.GetTempPath(),"vnrt-loose-check-"+Guid.NewGuid().ToString("N"));var result=await a.ExtractAsync([entry],output,true);Console.WriteLine($"LOOSE {a.Entries.Count} IMAGES {a.Entries.Count(e=>AssetClassifier.IsImage(e.Name))} VIDEOS {a.Entries.Count(e=>AssetClassifier.Classify(e.Name)==AssetCategory.Animation)} SAMPLE {entry.Name} {bytes.Length} EXTRACTED {result.Extracted}");Directory.Delete(output,true);return 0;}
    var paths = args.SelectMany(path => Directory.Exists(path) ? Directory.EnumerateFiles(path, "*.rpa", SearchOption.AllDirectories) : [path]).ToArray();
    foreach (var path in paths) { if (Path.GetExtension(path).Equals(".xp3", StringComparison.OrdinalIgnoreCase)) { var xp3 = Xp3Archive.Open(path); Console.WriteLine($"{path} | XP3 | {xp3.Entries.Count:N0} files | {xp3.Entries.Sum(e => e.Length):N0} bytes"); } else if(Path.GetExtension(path).Equals(".dat",StringComparison.OrdinalIgnoreCase)){var d=DpmxArchive.Open(path);Console.WriteLine($"{path} | DPMX | {d.Entries.Count:N0} files | {d.Entries.Sum(e=>e.Length):N0} bytes");} else { var archive = RpaArchive.Open(path); Console.WriteLine($"{path} | {archive.Version} | {archive.Entries.Count:N0} files | {archive.Entries.Sum(e => e.Length):N0} bytes"); } }
    Console.WriteLine($"已验证 {paths.Length} 个真实 RPA。\n");
    return 0;
}

var tests = new List<(string Name, Func<Task> Run)> { ("识别并读取标准 RPA-3.0", TestOpen), ("完整提取并校验内容", TestExtract), ("中文目录注释", TestChineseFolder), ("安全改名且不中断", TestUnsafeFilename), ("阻止路径穿越且不中断", TestTraversal), ("拒绝危险 Pickle 操作码", TestUnsafePickle), ("识别 XP3 文件头", TestXp3), ("读取 RPG Maker 普通资源", TestPlainRpgMaker), ("识别并复制散装视觉资源", TestLooseResources) };
var failures = 0;
foreach (var test in tests) { try { await test.Run(); Console.WriteLine($"PASS {test.Name}"); } catch (Exception ex) { failures++; Console.WriteLine($"FAIL {test.Name}: {ex.Message}"); } }
Console.WriteLine($"共 {tests.Count} 项，失败 {failures} 项。"); return failures;

static async Task TestOpen() { using var f = CreateRpa("images/test.txt", "hello-rpa"u8.ToArray()); var a = await RpaArchive.OpenAsync(f.Archive); Assert(a.Version == "RPA-3.0", "版本不正确"); Assert(a.Entries.Count == 1, "文件数不正确"); Assert(a.Entries[0].Name == "images/test.txt", "文件名不正确"); }
static async Task TestExtract() { var content = Encoding.UTF8.GetBytes("中文路径和内容"); using var f = CreateRpa("图片/测试.txt", content); var a = RpaArchive.Open(f.Archive); var output = Path.Combine(f.Root, "out"); var r = await a.ExtractAllAsync(output, false); Assert(r.Extracted == 1, "提取计数不正确"); Assert(File.ReadAllBytes(Path.Combine(output, "图片", "测试.txt")).SequenceEqual(content), "提取内容不一致"); }
static async Task TestChineseFolder() { using var f=CreateRpa("bg/room.png","image"u8.ToArray());var a=RpaArchive.Open(f.Archive);var output=Path.Combine(f.Root,"out");await a.ExtractAsync(a.Entries,output,false,null,default,true);Assert(File.Exists(Path.Combine(output,"bg-背景","room.png")),"中文目录注释失败"); }
static async Task TestUnsafeFilename() { using var f = CreateRpa("images/a:b?.png", "image"u8.ToArray()); var a = RpaArchive.Open(f.Archive); var output=Path.Combine(f.Root,"out");var result=await a.ExtractAllAsync(output,false);Assert(result.Extracted==1&&result.Renamed==1,"特殊字符文件没有安全改名");Assert(Directory.EnumerateFiles(output,"*.png",SearchOption.AllDirectories).Count()==1,"改名后的文件不存在"); }
static async Task TestTraversal() { using var f = CreateRpa("../escape.txt", "blocked"u8.ToArray()); var a = RpaArchive.Open(f.Archive); var result=await a.ExtractAllAsync(Path.Combine(f.Root, "out"), false);Assert(result.Failed==1&&result.Extracted==0,"没有隔离路径穿越文件"); }
static async Task TestUnsafePickle() { using var f = CreateRawRpa([0x80,0x02,(byte)'c',(byte)'o',(byte)'s',(byte)'\n',(byte)'s',(byte)'y',(byte)'s',(byte)'t',(byte)'e',(byte)'m',(byte)'\n',(byte)'.']); await AssertThrows<InvalidDataException>(() => Task.Run(() => RpaArchive.Open(f.Archive)), "危险 Pickle 未被拒绝"); }
static Task TestXp3() { var root = NewTemp(); var path = Path.Combine(root, "data.xp3"); File.WriteAllBytes(path, [0x58,0x50,0x33,0x0d,0x0a,0x20,0x0a,0x1a,0x8b,0x67,0x01]); try { var r = new GameScanner().InspectFile(path); Assert(r.Kind == ResourceKind.KirikiriXp3 && r.Support == SupportLevel.Recognized, "XP3 识别失败"); } finally { Directory.Delete(root, true); } return Task.CompletedTask; }
static async Task TestPlainRpgMaker(){var root=NewTemp();try{var www=Path.Combine(root,"www");Directory.CreateDirectory(Path.Combine(www,"js"));Directory.CreateDirectory(Path.Combine(www,"img","pictures"));File.WriteAllText(Path.Combine(www,"js","rpg_core.js"),"RPG Maker");var content="plain-png"u8.ToArray();File.WriteAllBytes(Path.Combine(www,"img","pictures","scene.png"),content);var project=RpgMakerProject.Open(root);Assert(project.Entries is [{Encrypted:false}],"普通 RPG Maker 图片未进入索引");var output=Path.Combine(root,"out");var result=await project.ExtractAsync(project.Entries,output,true);Assert(result.Extracted==1&&File.ReadAllBytes(Path.Combine(output,"img","pictures","scene.png")).SequenceEqual(content),"普通 RPG Maker 图片复制失败");}finally{Directory.Delete(root,true);}}
static async Task TestLooseResources(){var root=NewTemp();try{var game=Path.Combine(root,"game");Directory.CreateDirectory(Path.Combine(game,"images"));for(var i=0;i<5;i++)File.WriteAllBytes(Path.Combine(game,"images",$"{i}.png"),[(byte)('0'+i)]);var scan=new GameScanner().Scan(root);Assert(scan.Any(r=>r.Kind==ResourceKind.AlreadyUnpacked),"散装视觉资源未识别");var project=LooseResourceProject.Open(root);var output=Path.Combine(root,"out");var result=await project.ExtractAsync([project.Entries[0]],output,true);Assert(result.Extracted==1,"散装视觉资源复制失败");}finally{Directory.Delete(root,true);}}

static TempFixture CreateRpa(string name, byte[] content)
{
    const int key = 0x42424242; const int dataOffset = 34; var encodedOffset = dataOffset ^ key; var encodedLength = content.Length ^ key;
    using var pickle = new MemoryStream(); pickle.Write([0x80,0x02,(byte)'}',(byte)'q',0,(byte)'U',(byte)Encoding.UTF8.GetByteCount(name)]); pickle.Write(Encoding.UTF8.GetBytes(name)); pickle.Write([(byte)'q',1,(byte)']',(byte)'q',2,(byte)'J']); WriteInt(pickle, (int)encodedOffset); pickle.Write([(byte)'J']); WriteInt(pickle, encodedLength); pickle.Write([0x86,(byte)'q',3,(byte)'a',(byte)'s',(byte)'.']);
    var root = NewTemp(); var archive = Path.Combine(root, "test.rpa"); using var file = File.Create(archive); var indexOffset = dataOffset + content.Length; file.Write(Encoding.ASCII.GetBytes($"RPA-3.0 {indexOffset:x16} {key:x8}\n")); file.Write(content); using (var z = new ZLibStream(file, CompressionLevel.Optimal, true)) z.Write(pickle.ToArray()); return new(root, archive);
}
static TempFixture CreateRawRpa(byte[] pickle) { var root = NewTemp(); var archive = Path.Combine(root, "unsafe.rpa"); using var file = File.Create(archive); file.Write(Encoding.ASCII.GetBytes("RPA-3.0 0000000000000022 00000000\n")); using (var z = new ZLibStream(file, CompressionLevel.Optimal, true)) z.Write(pickle); return new(root, archive); }
static void WriteInt(Stream stream, int value) => stream.Write(BitConverter.GetBytes(value));
static string NewTemp() { var path = Path.Combine(Path.GetTempPath(), "vnrt-tests-" + Guid.NewGuid().ToString("N")); Directory.CreateDirectory(path); return path; }
static void Assert(bool condition, string message) { if (!condition) throw new Exception(message); }
static async Task AssertThrows<T>(Func<Task> action, string message) where T : Exception { try { await action(); } catch (T) { return; } throw new Exception(message); }
sealed class TempFixture(string root, string archive) : IDisposable { public string Root { get; } = root; public string Archive { get; } = archive; public void Dispose() { try { Directory.Delete(Root, true); } catch { } } }
