using Microsoft.Win32;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.Diagnostics;
using System.IO;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Threading;
using VisualNovelResourceTool.Core;

namespace VisualNovelResourceTool.App;

public partial class MainWindow : Window
{
    private readonly GameScanner _scanner = new(); private readonly ObservableCollection<ResultRow> _results = []; private readonly ObservableCollection<object> _visibleEntries = []; private readonly ObservableCollection<NearbyPreview> _nearby = [];
    private readonly AppSettings _settings = AppSettings.Load(); private RpaArchive? _rpa; private Xp3Archive? _xp3; private RpgMakerProject? _rpg; private RpgMakerPakArchive? _pak; private LooseResourceProject? _loose; private DpmxArchive? _dpmx; private CancellationTokenSource? _operation; private string? _archivePath; private string? _selectedGameRoot; private string? _enigmaExe; private DispatcherTimer? _gifTimer; private IReadOnlyList<BitmapFrame>? _gifFrames; private int _gifFrame;private int _nearbyVersion;private int _videoVersion;private string? _videoCache;private Point _dragStart;private bool _dragging;private bool _dragCandidate;
    public MainWindow() { InitializeComponent(); ResultsGrid.ItemsSource = _results; EntriesList.ItemsSource = _visibleEntries; NearbyStrip.ItemsSource=_nearby;EntriesList.PreviewMouseLeftButtonDown+=EntriesList_PreviewMouseLeftButtonDown;EntriesList.PreviewMouseLeftButtonUp+=(_,_)=>_dragCandidate=false;EntriesList.PreviewMouseMove+=EntriesList_PreviewMouseMove;Closed+=(_,_)=>StopVideoPreview();CustomOutputBox.IsChecked = _settings.UseCustomOutputRoot; ChineseFolderBox.IsChecked = _settings.AddChineseDirectoryLabels; OutputRootBox.Text = _settings.UseCustomOutputRoot ? _settings.CustomOutputRoot : "所选游戏根目录\\解包结果\\资源包名";CleanDragCache(); }
    private async void ChooseFolder_Click(object s, RoutedEventArgs e) { var d = new OpenFolderDialog { Title="选择视觉小说目录" }; if(d.ShowDialog()==true) await ScanAsync(d.FolderName); }
    private async void ChooseArchive_Click(object s, RoutedEventArgs e) { var d = new OpenFileDialog { Filter="支持的资源包或单文件游戏|*.rpa;*.xp3;*.exe|所有文件|*.*" }; if(d.ShowDialog()==true) await ScanAsync(d.FileName); }
    private async void Decompile_Click(object s,RoutedEventArgs e){var d=new OpenFolderDialog{Title="选择含有 RPyC 的 Ren’Py 游戏目录"};if(d.ShowDialog()!=true)return;var output=_settings.GetOutput(Path.Combine(d.FolderName,"scripts.rpa"))+"_反编译脚本";_operation=new();SetBusy(true,"正在复制并反编译脚本……");try{var result=await UnrpycService.DecompileAsync(d.FolderName,output,_operation.Token);StatusText.Text=$"已反编译 {result.Files} 个脚本；位置：{output}";MessageBox.Show($"脚本已输出到：\n{output}","反编译完成");}catch(Exception ex){Error("反编译失败",ex);}finally{SetBusy(false);}}
    private async void Window_Drop(object s, DragEventArgs e) { if(e.Data.GetData(DataFormats.FileDrop) is string[] {Length:>0} p) await ScanAsync(p[0]); }
    private void Window_DragOver(object s, DragEventArgs e) => e.Effects=e.Data.GetDataPresent(DataFormats.FileDrop)?DragDropEffects.Copy:DragDropEffects.None;
    private void ChooseOutput_Click(object s, RoutedEventArgs e) { var d=new OpenFolderDialog{Title="选择固定的默认输出位置"}; if(d.ShowDialog()==true){_settings.CustomOutputRoot=d.FolderName;_settings.UseCustomOutputRoot=true;CustomOutputBox.IsChecked=true;OutputRootBox.Text=d.FolderName;_settings.Save();UpdateOutputPreview();} }
    private void OutputSetting_Changed(object s, RoutedEventArgs e) { if(!IsLoaded)return;_settings.UseCustomOutputRoot=CustomOutputBox.IsChecked==true; OutputRootBox.Text=_settings.UseCustomOutputRoot?(_settings.CustomOutputRoot.Length>0?_settings.CustomOutputRoot:"请点击“更改位置”"):"所选游戏根目录\\解包结果\\资源包名";_settings.Save();UpdateOutputPreview(); }
    private void ChineseFolder_Changed(object s,RoutedEventArgs e){if(!IsLoaded)return;_settings.AddChineseDirectoryLabels=ChineseFolderBox.IsChecked==true;_settings.Save();}
    private async Task ScanAsync(string path){Cancel();SetBusy(true,"正在扫描……");PathBox.Text=path;_selectedGameRoot=Directory.Exists(path)?Path.GetFullPath(path):null;_results.Clear();ClearArchive();try{foreach(var x in await _scanner.ScanAsync(path))_results.Add(new(x));if(_results.Count>0){var looseIndex=_results.Select((row,index)=>(row,index)).FirstOrDefault(x=>x.row.Source.Kind==ResourceKind.AlreadyUnpacked).index;ResultsGrid.SelectedIndex=looseIndex;}StatusText.Text=$"发现 {_results.Count} 项。";}catch(Exception ex){Error("扫描失败",ex);}finally{SetBusy(false);}}
    private async void ResultsGrid_SelectionChanged(object s, SelectionChangedEventArgs e){if(ResultsGrid.SelectedItem is not ResultRow row)return;ClearArchive();_archivePath=row.Source.Path;DetailTitle.Text=row.DisplayName;DetailDescription.Text=row.Source.Description;UpdateOutputPreview();try{if(row.Source.Kind==ResourceKind.EnigmaExecutable){_enigmaExe=row.Source.Path;ExtractAllButton.IsEnabled=true;ExtractAllButton.Content="提取 EXE 中的图片";EntryCountText.Text="单文件封装将在提取时读取；只保留图片和动图。";}else if(row.Source.Kind==ResourceKind.RenPyRpa&&row.Source.Support==SupportLevel.Extractable){SetBusy(true,"读取 RPA 索引……");_rpa=await RpaArchive.OpenAsync(row.Source.Path);ShowEntries(_rpa.Entries.Cast<object>());}else if(row.Source.Kind==ResourceKind.KirikiriXp3&&row.Source.Support==SupportLevel.Recognized){SetBusy(true,"读取 XP3 索引……");_xp3=await Task.Run(()=>Xp3Archive.Open(row.Source.Path));ShowEntries(_xp3.Entries.Cast<object>());DetailDescription.Text="标准 XP3，可浏览和提取。";}else if(row.Source.Kind==ResourceKind.RpgMaker){SetBusy(true,"检查 RPG Maker 资源……");_rpg=await Task.Run(()=>RpgMakerProject.Open(row.Source.Path));ShowEntries(_rpg.Entries.Cast<object>());DetailDescription.Text=_rpg.Entries.Any(e=>e.Encrypted)?(_rpg.EncryptionKey is null?"发现加密资源，但没有找到项目密钥。":"已找到项目密钥，可还原加密图片和音频。") : "资源已经解开，可直接预览、分类、复制或拖出。";}else if(row.Source.Kind==ResourceKind.RpgMakerPak){SetBusy(true,"读取 RPG Maker data.pak……");_pak=await Task.Run(()=>RpgMakerPakArchive.Open(row.Source.Path));ShowEntries(_pak.Entries.Cast<object>());DetailDescription.Text="已读取加密 data.pak，可预览并提取图片和视频。";}else if(row.Source.Kind==ResourceKind.AlreadyUnpacked){SetBusy(true,"读取散装视觉资源……");_loose=await Task.Run(()=>LooseResourceProject.Open(row.Source.Path));ShowEntries(_loose.Entries.Cast<object>());DetailDescription.Text="资源已经解开，可直接预览、分类、复制或拖出。";}else if(row.Source.Kind==ResourceKind.Dpmx){SetBusy(true,"读取 DPMX 索引……");_dpmx=await Task.Run(()=>DpmxArchive.Open(row.Source.Path));ShowEntries(_dpmx.Entries.Cast<object>());}}catch(Exception ex){DetailDescription.Text="读取失败："+ex.Message;}finally{SetBusy(false);}}
    private void ShowEntries(IEnumerable<object> entries){ExtractAllButton.Content="提取当前分类";_visibleEntries.Clear();foreach(var x in entries)_visibleEntries.Add(x);EntryCountText.Text=$"{_visibleEntries.Count:N0} 个文件；可按 Ctrl/Shift 多选";ExtractAllButton.IsEnabled=_visibleEntries.Count>0;ApplyFilter();StatusText.Text=_visibleEntries.Count==0?"索引读取完成，但当前“图片”分类中没有文件；可切换到“全部资源（高级）”查看。":$"索引读取完成，当前显示 {_visibleEntries.Count:N0} 个文件。";}
    private void Filter_Changed(object s, TextChangedEventArgs e)=>ApplyFilter();
    private void Category_Changed(object s, SelectionChangedEventArgs e)=>ApplyFilter();
    private void ApplyFilter(){if(!IsLoaded)return;IEnumerable<object> source=_rpa?.Entries.Cast<object>()??_xp3?.Entries.Cast<object>()??_rpg?.Entries.Cast<object>()??_pak?.Entries.Cast<object>()??_loose?.Entries.Cast<object>()??_dpmx?.Entries.Cast<object>()??[];var q=FilterBox.Text.Trim();var category=Enum.TryParse<AssetCategory>(CategoryBox.SelectedValue?.ToString(),out var c)?c:AssetCategory.Images;_visibleEntries.Clear();foreach(var x in source.Where(x=>AssetClassifier.Matches(GetName(x),category)&&(q.Length==0||GetName(x).Contains(q,StringComparison.OrdinalIgnoreCase))))_visibleEntries.Add(x);EntryCountText.Text=$"显示 {_visibleEntries.Count:N0} 个文件";ExtractAllButton.IsEnabled=_visibleEntries.Count>0;ThumbnailButton.IsEnabled=_visibleEntries.Any(x=>AssetClassifier.IsImage(GetName(x)));}
    private async void Entries_SelectionChanged(object s, SelectionChangedEventArgs e){ExtractSelectedButton.IsEnabled=EntriesList.SelectedItems.Count>0;StopGif();StopVideoPreview();PreviewImage.Source=null;var selected=EntriesList.SelectedItem;var name=selected is null?"":GetName(selected);if(selected is not null)_=LoadNearbyAsync(selected);if(selected is not null&&IsVideo(name)){await PreviewVideoAsync(selected,name);return;}if(!AssetClassifier.IsImage(name))return;try{var bytes=selected is null?null:await ReadPreviewBytesAsync(selected);if(bytes is null)return;using var m=new MemoryStream(bytes);if(Path.GetExtension(name).Equals(".gif",StringComparison.OrdinalIgnoreCase))ShowAnimatedGif(m);else{var image=new BitmapImage();image.BeginInit();image.CacheOption=BitmapCacheOption.OnLoad;image.StreamSource=m;image.EndInit();image.Freeze();PreviewImage.Source=image;}}catch(Exception ex){DetailDescription.Text=$"该图片暂时无法预览（仍可正常提取）：{ex.Message}";}}
    private void ShowAnimatedGif(Stream stream){var decoder=new GifBitmapDecoder(stream,BitmapCreateOptions.PreservePixelFormat,BitmapCacheOption.OnLoad);_gifFrames=decoder.Frames.ToArray();_gifFrame=0;PreviewImage.Source=_gifFrames[0];if(_gifFrames.Count<=1)return;_gifTimer=new DispatcherTimer{Interval=TimeSpan.FromMilliseconds(140)};_gifTimer.Tick+=(_,_)=>{if(_gifFrames is {Count:>0})PreviewImage.Source=_gifFrames[_gifFrame=(_gifFrame+1)%_gifFrames.Count];};_gifTimer.Start();}
    private void StopGif(){_gifTimer?.Stop();_gifTimer=null;_gifFrames=null;}
    private static bool IsVideo(string name)=>Path.GetExtension(name).ToLowerInvariant() is ".webm" or ".mp4" or ".ogv" or ".avi";
    private async Task PreviewVideoAsync(object entry,string name){var version=++_videoVersion;var cache=Path.Combine(Path.GetTempPath(),"vnrt-preview-"+Guid.NewGuid().ToString("N"));Directory.CreateDirectory(cache);_videoCache=cache;DetailDescription.Text="正在生成轻量动态预览……";try{if(_rpa is not null)await _rpa.ExtractAsync([(RpaEntry)entry],cache,true);else if(_xp3 is not null)await _xp3.ExtractAsync([(Xp3Entry)entry],cache,true);else if(_pak is not null)await _pak.ExtractAsync([(PakEntry)entry],cache,true);else if(_rpg is not null)await _rpg.ExtractAsync([(RpgMakerEntry)entry],cache,true);else if(_loose is not null)await _loose.ExtractAsync([(LooseEntry)entry],cache,true);else return;if(version!=_videoVersion)return;var file=Directory.EnumerateFiles(cache,"*",SearchOption.AllDirectories).FirstOrDefault(f=>Path.GetExtension(f).Equals(Path.GetExtension(name),StringComparison.OrdinalIgnoreCase));if(file is null)throw new FileNotFoundException("临时视频文件未生成。");var gif=Path.Combine(cache,"preview.gif");using var process=Process.Start(new ProcessStartInfo("ffmpeg.exe") {UseShellExecute=false,CreateNoWindow=true,RedirectStandardError=true,ArgumentList={"-v","error","-ss","0","-i",file,"-t","6","-vf","fps=7,scale=560:-2:flags=lanczos","-an","-y",gif}})??throw new InvalidOperationException("无法启动 FFmpeg。");var errorTask=process.StandardError.ReadToEndAsync();await process.WaitForExitAsync();var error=await errorTask;if(process.ExitCode!=0||!File.Exists(gif))throw new InvalidDataException(string.IsNullOrWhiteSpace(error)?"FFmpeg 无法解码该视频。":error.Trim());if(version!=_videoVersion)return;using var stream=File.OpenRead(gif);ShowAnimatedGif(stream);DetailDescription.Text="视频预览：前 6 秒、静音循环（原文件不受影响）。";}catch(System.ComponentModel.Win32Exception){if(version==_videoVersion)DetailDescription.Text="无法预览 WebM：未找到 FFmpeg。仍可正常提取原视频。";}catch(Exception ex){if(version==_videoVersion)DetailDescription.Text=$"该视频暂时无法预览（仍可正常提取）：{ex.Message}";}}
    private void PreviewVideo_Ended(object s,RoutedEventArgs e){}
    private void PreviewVideo_Failed(object s,ExceptionRoutedEventArgs e){}
    private void StopVideoPreview(){_videoVersion++;try{PreviewVideo.Stop();PreviewVideo.Close();PreviewVideo.Source=null;PreviewVideo.Visibility=Visibility.Collapsed;}catch{}var cache=_videoCache;_videoCache=null;if(cache is not null)try{var full=Path.GetFullPath(cache);if(full.StartsWith(Path.GetFullPath(Path.GetTempPath()),StringComparison.OrdinalIgnoreCase)&&Path.GetFileName(full).StartsWith("vnrt-preview-",StringComparison.Ordinal))Directory.Delete(full,true);}catch{}}
    private async Task LoadNearbyAsync(object selected){var version=++_nearbyVersion;var images=_visibleEntries.Where(x=>AssetClassifier.IsImage(GetName(x))).ToArray();var at=Array.IndexOf(images,selected);if(at<0){_nearby.Clear();return;}var start=Math.Clamp(at-2,0,Math.Max(0,images.Length-5));var items=images.Skip(start).Take(5).ToArray();_nearby.Clear();foreach(var item in items)_nearby.Add(new(item,null,GetName(item)));for(var i=0;i<items.Length;i++){try{var bytes=await ReadPreviewBytesAsync(items[i],4*1024*1024);if(version!=_nearbyVersion||bytes is null)return;using var stream=new MemoryStream(bytes);var bitmap=new BitmapImage();bitmap.BeginInit();bitmap.CacheOption=BitmapCacheOption.OnLoad;bitmap.DecodePixelWidth=100;bitmap.StreamSource=stream;bitmap.EndInit();bitmap.Freeze();_nearby[i]=new(items[i],bitmap,GetName(items[i]));}catch{}}}
    private void Nearby_Click(object s,RoutedEventArgs e){if(s is Button{Tag:object entry}){EntriesList.SelectedItem=entry;EntriesList.ScrollIntoView(entry);}}
    private async void ExtractAll_Click(object s,RoutedEventArgs e)=>await ExtractAsync(false);
    private async void ExtractSelected_Click(object s,RoutedEventArgs e)=>await ExtractAsync(true);
    private void Thumbnail_Click(object s,RoutedEventArgs e){var images=_visibleEntries.Where(x=>AssetClassifier.IsImage(GetName(x))).ToArray();new ThumbnailWindow(images,x=>ReadPreviewBytesAsync(x),GetName){Owner=this}.Show();}
    private async Task<byte[]?> ReadPreviewBytesAsync(object entry,int maximumBytes=16*1024*1024)=>entry switch{RpaEntry r=>await _rpa!.ReadEntryAsync(r,maximumBytes),Xp3Entry x=>await _xp3!.ReadEntryAsync(x,maximumBytes),PakEntry p=>await _pak!.ReadEntryAsync(p,maximumBytes),RpgMakerEntry g=>await ReadRpgMakerPreviewAsync(g,maximumBytes),LooseEntry l=>await _loose!.ReadEntryAsync(l,maximumBytes),_=>null};
    private async Task<byte[]> ReadRpgMakerPreviewAsync(RpgMakerEntry entry,int maximumBytes){if(entry.Length>maximumBytes)throw new InvalidDataException($"文件过大，无法预览（{entry.Length:N0} 字节）。");if(!entry.Encrypted)return await File.ReadAllBytesAsync(entry.SourcePath);var key=_rpg?.EncryptionKey??throw new InvalidDataException("缺少 RPG Maker 解密密钥。");var data=await File.ReadAllBytesAsync(entry.SourcePath);if(data.Length<16)throw new InvalidDataException("加密文件过短。");var plain=data[16..];for(var i=0;i<Math.Min(16,plain.Length);i++)plain[i]^=key[i%key.Length];return plain;}
    private async Task ExtractAsync(bool selected){if(_archivePath is null)return;var output=_settings.GetOutput(_archivePath,_selectedGameRoot);Directory.CreateDirectory(output);var list=selected?EntriesList.SelectedItems.Cast<object>().ToArray():_visibleEntries.ToArray();_operation=new();SetBusy(true,_enigmaExe is null?"准备提取……":"正在展开单文件 EXE 并筛选图片，可能需要几分钟……");Progress.Visibility=Visibility.Visible;Progress.IsIndeterminate=_enigmaExe is not null;var reporter=new Progress<ExtractionProgress>(p=>{Progress.Value=p.Total==0?0:p.Completed*100d/p.Total;StatusText.Text=$"{p.Completed:N0}/{p.Total:N0} {p.CurrentFile}";});try{var labels=_settings.AddChineseDirectoryLabels;ExtractionSummary result;if(_enigmaExe is not null)result=await EnigmaExtractorService.ExtractVisualsAsync(_enigmaExe,output,OverwriteBox.IsChecked==true,labels,_operation.Token);else if(_rpa is not null)result=await _rpa.ExtractAsync(list.Cast<RpaEntry>(),output,OverwriteBox.IsChecked==true,reporter,_operation.Token,labels);else if(_xp3 is not null)result=await _xp3.ExtractAsync(list.Cast<Xp3Entry>(),output,OverwriteBox.IsChecked==true,reporter,_operation.Token,labels);else if(_rpg is not null)result=await _rpg.ExtractAsync(list.Cast<RpgMakerEntry>(),output,OverwriteBox.IsChecked==true,reporter,_operation.Token,labels);else if(_pak is not null)result=await _pak.ExtractAsync(list.Cast<PakEntry>(),output,OverwriteBox.IsChecked==true,reporter,_operation.Token,labels);else if(_loose is not null)result=await _loose.ExtractAsync(list.Cast<LooseEntry>(),output,OverwriteBox.IsChecked==true,reporter,_operation.Token,labels);else result=await _dpmx!.ExtractAsync(list.Cast<DpmxEntry>(),output,OverwriteBox.IsChecked==true,reporter,_operation.Token);StatusText.Text=$"完成：提取 {result.Extracted}，跳过 {result.Skipped}，失败 {result.Failed}，重命名 {result.Renamed}。位置：{output}";OutputPreviewText.Text=$"最近完成：\n{output}\n提取 {result.Extracted}，跳过 {result.Skipped}，失败 {result.Failed}";}catch(OperationCanceledException){StatusText.Text="已取消。";}catch(Exception ex){Error("提取失败",ex);}finally{SetBusy(false);Progress.IsIndeterminate=false;Progress.Visibility=Visibility.Collapsed;}}
    private void UpdateOutputPreview(){OutputPreviewText.Text=_archivePath is null?"选择资源包后显示输出位置":$"将提取到：\n{_settings.GetOutput(_archivePath,_selectedGameRoot)}";}
    private void ClearArchive(){StopGif();StopVideoPreview();_nearbyVersion++;_nearby.Clear();_rpa=null;_xp3=null;_rpg=null;_pak=null;_loose=null;_dpmx=null;_enigmaExe=null;_archivePath=null;_visibleEntries.Clear();PreviewImage.Source=null;ExtractAllButton.Content="提取当前分类";ExtractAllButton.IsEnabled=ExtractSelectedButton.IsEnabled=ThumbnailButton.IsEnabled=false;}
    private static string GetName(object x)=>x switch{RpaEntry r=>r.Name,Xp3Entry p=>p.Name,RpgMakerEntry g=>g.RelativeOutputPath,PakEntry p=>p.Name,LooseEntry l=>l.Name,DpmxEntry d=>d.Name,_=>""};
    private void EntriesList_PreviewMouseLeftButtonDown(object s,System.Windows.Input.MouseButtonEventArgs e){var source=e.OriginalSource as DependencyObject;var point=e.GetPosition(EntriesList);_dragCandidate=FindAncestor<ScrollBar>(source) is null&&FindAncestor<ListBoxItem>(source) is not null&&FindAncestor<TextBlock>(source) is not null&&point.X<EntriesList.ActualWidth-SystemParameters.VerticalScrollBarWidth-8;if(_dragCandidate)_dragStart=point;}
    private static T? FindAncestor<T>(DependencyObject? value)where T:DependencyObject{while(value is not null){if(value is T match)return match;value=VisualTreeHelper.GetParent(value);}return null;}
    private async void EntriesList_PreviewMouseMove(object s,System.Windows.Input.MouseEventArgs e)
    {
        if(!_dragCandidate||_dragging||e.LeftButton!=System.Windows.Input.MouseButtonState.Pressed||EntriesList.SelectedItems.Count==0)return;var point=e.GetPosition(EntriesList);var dx=Math.Abs(point.X-_dragStart.X);var dy=Math.Abs(point.Y-_dragStart.Y);if(dx<SystemParameters.MinimumHorizontalDragDistance||dx<dy*1.5)return;
        _dragCandidate=false;_dragging=true;try{var selected=EntriesList.SelectedItems.Cast<object>().ToArray();var cache=Path.Combine(DragCacheRoot,Guid.NewGuid().ToString("N"));Directory.CreateDirectory(cache);StatusText.Text=$"正在准备拖出 {selected.Length} 个文件……";if(_rpa is not null)await _rpa.ExtractAsync(selected.Cast<RpaEntry>(),cache,true);else if(_xp3 is not null)await _xp3.ExtractAsync(selected.Cast<Xp3Entry>(),cache,true);else if(_rpg is not null)await _rpg.ExtractAsync(selected.Cast<RpgMakerEntry>(),cache,true);else if(_pak is not null)await _pak.ExtractAsync(selected.Cast<PakEntry>(),cache,true);else if(_loose is not null)await _loose.ExtractAsync(selected.Cast<LooseEntry>(),cache,true);else if(_dpmx is not null)await _dpmx.ExtractAsync(selected.Cast<DpmxEntry>(),cache,true);else return;var files=Directory.EnumerateFiles(cache,"*",SearchOption.AllDirectories).Where(f=>!Path.GetFileName(f).Equals("_提取记录.txt",StringComparison.OrdinalIgnoreCase)).ToArray();if(files.Length==0)return;var collection=new StringCollection();collection.AddRange(files);var data=new DataObject();data.SetFileDropList(collection);StatusText.Text="可拖放到资源管理器或桌面。";DragDrop.DoDragDrop(EntriesList,data,DragDropEffects.Copy);}catch(Exception ex){Error("拖出失败",ex);}finally{_dragging=false;}}
    private static string DragCacheRoot=>Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData),"视觉小说资源工具","拖出缓存");
    private static void CleanDragCache(){try{if(!Directory.Exists(DragCacheRoot))return;foreach(var directory in Directory.EnumerateDirectories(DragCacheRoot)){var info=new DirectoryInfo(directory);if(info.CreationTimeUtc<DateTime.UtcNow.AddDays(-1))Directory.Delete(directory,true);}}catch{}}
    private void Cancel_Click(object s,RoutedEventArgs e)=>Cancel(); private void Cancel(){_operation?.Cancel();_operation?.Dispose();_operation=null;} private void SetBusy(bool busy,string? text=null){CancelButton.IsEnabled=busy;if(text!=null)StatusText.Text=text;} private void Error(string title,Exception ex){StatusText.Text=title+"："+ex.Message;MessageBox.Show(ex.Message,title);}
}
public sealed class ResultRow{public ScanResult Source{get;}public string DisplayName=>Source.DisplayName;public string Format=>Source.Format;public string StatusText=>Source.Support switch{SupportLevel.Extractable=>"可提取",SupportLevel.Recognized=>"已识别",SupportLevel.NoExtractionNeeded=>"无需解包",SupportLevel.Error=>"异常",_=>"暂不支持"};public ResultRow(ScanResult s)=>Source=s;}
public sealed record NearbyPreview(object Entry,ImageSource? Source,string Name);
