using System.Buffers.Binary;
using System.Text;
namespace VisualNovelResourceTool.Core;
public sealed class DpmxArchive
{
 public string Path{get;} public IReadOnlyList<DpmxEntry> Entries{get;} private DpmxArchive(string p,IReadOnlyList<DpmxEntry> e)=>(Path,Entries)=(p,e);
 public static DpmxArchive Open(string path,CancellationToken token=default){token.ThrowIfCancellationRequested();Encoding.RegisterProvider(CodePagesEncodingProvider.Instance);using var f=File.OpenRead(path);var h=Read(f,16);if(Encoding.ASCII.GetString(h,0,4)!="DPMX")throw new InvalidDataException("不是 DPMX 资源包。");var start=BinaryPrimitives.ReadUInt32LittleEndian(h.AsSpan(4));var count=BinaryPrimitives.ReadUInt32LittleEndian(h.AsSpan(8));if(start!=16+count*32L||start>f.Length)throw new InvalidDataException("DPMX 索引无效。");var enc=Encoding.GetEncoding(932);var list=new List<DpmxEntry>();for(var i=0;i<count;i++){token.ThrowIfCancellationRequested();var b=Read(f,32);var end=Array.IndexOf(b,(byte)0,0,16);if(end<0)end=16;var name=enc.GetString(b,0,end);var rel=BinaryPrimitives.ReadUInt32LittleEndian(b.AsSpan(24));var len=BinaryPrimitives.ReadUInt32LittleEndian(b.AsSpan(28));var off=(long)start+rel;if(off>f.Length||len>f.Length-off)throw new InvalidDataException($"DPMX 条目越界：{name}");list.Add(new(name,off,len));}return new(path,list);}
 public async Task<ExtractionSummary> ExtractAsync(IEnumerable<DpmxEntry> selected,string output,bool overwrite,IProgress<ExtractionProgress>? progress=null,CancellationToken token=default){var items=selected.ToArray();var paths=new SafeExtractionPath(output);await using var src=new FileStream(Path,FileMode.Open,FileAccess.Read,FileShare.Read,1048576,FileOptions.Asynchronous|FileOptions.RandomAccess);var buffer=new byte[1048576];var done=0;var skip=0;var failed=0;long written=0;var failures=new List<string>();for(var i=0;i<items.Length;i++){token.ThrowIfCancellationRequested();var e=items[i];string? temp=null;try{var target=paths.Resolve(e.Name);if(!overwrite&&File.Exists(target)){skip++;continue;}Directory.CreateDirectory(System.IO.Path.GetDirectoryName(target)!);temp=SafeExtractionPath.TemporaryPath(target);await using var dst=new FileStream(temp, FileMode.CreateNew, FileAccess.Write, FileShare.None);src.Position=e.Offset;var left=e.Length;while(left>0){var n=await src.ReadAsync(buffer.AsMemory(0,(int)Math.Min(left,buffer.Length)),token);if(n==0)throw new EndOfStreamException();await dst.WriteAsync(buffer.AsMemory(0,n),token);left-=n;written+=n;}await dst.DisposeAsync();File.Move(temp,target,overwrite);done++;}catch(OperationCanceledException){if(temp is not null&&File.Exists(temp))File.Delete(temp);throw;}catch(Exception ex){if(temp is not null&&File.Exists(temp))File.Delete(temp);failed++;failures.Add($"{e.Name}: {ex.Message}");}finally{progress?.Report(new(i+1,items.Length,e.Name,written));}}paths.WriteReport(failures);return new(done,skip,written,output,failed,paths.Renamed);}
 private static byte[] Read(Stream s,int n){var b=new byte[n];s.ReadExactly(b);return b;}
}
